name: Test and lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: sbt
      - name: Check proper code formatting
        run: sbt check

  test:
    runs-on: ubuntu-22.04
    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: sbt
      - name: Cross compile and cross run tests
        run: sbt +test
